### ISSUE TITLE
Failed to create output directory ./cache/views

### ISSUE THREAD

**Issue by aavrug** [clthck/cakephp-jade#2]
Done with step by step setup as guided but getting error when trying to reload the .ctp.jade file "**Failed to create output directory ./cache/views**"

**Comment by clthck** [comment]
@aavrug I'll check the issue. thanks for reporting this.

**Comment by clthck** [comment]
can you please check if `tmp` folder is writable in your project?

**Comment by aavrug** [comment]
I have fixed and created a PR.

**Comment by clthck** [comment]
I know but please confirm that your tmp folder is writable.

**Comment by aavrug** [comment]
Yes I my application's tmp folder is having 777 permission.

**Comment by clthck** [comment]
I'll review and update you soon.

**Comment by aavrug** [comment]
Ok

**Comment by clthck** [comment]
Merged the PR. Please try the latest commit in your app and let me know if the issue is fixed.
